### ISSUE TITLE
Tilby SPARQL søk mot datakatalogens endepunkt

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-sparql-gui#3]
Hentet fra behov: https://github.com/Informasjonsforvaltning/behov/issues/159
Legg frontend på denne siden:
https://data.norge.no/sparql

Litt inspirasjon:
https://datos.gob.es/en/sparql
Deichmans bibliotek

Oppgaver: 
- [x] Vurdere hvordan dette skal gjøres

- [x] Gjøre dette brukervennlig f.eks med en enkel frontend (se f.eks den spanske siden)

**Comment by jeffreiffers** [comment]
Første utkast (inkl. nettleser vindu)

![image](https://user-images.githubusercontent.com/430997/115862331-4f435700-a434-11eb-9c64-ea69d9f5f3ac.png)
