### ISSUE TITLE
Lage dokumentasjon/eksempler side til SPARQL Endepunkt

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/fdk-sparql-gui#4]
Bruke CMS?

**Comment by stigbd** [comment]
Ja, bruk CMS, ref diskusjonen eg starta i Slack: https://fdk-project.slack.com/archives/C7D69GE8L/p1619090811090000

**Comment by KjerstiSteien** [comment]
Regnes som løst. Sparql er beskrevet her: https://informasjonsforvaltning.github.io/data.norge.no/search/sparql/ Vi vil fortsette å utvide eksempler fremover.
